### ISSUE TITLE
(IE10) campo de "adicionar novo" está cortado

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-landing#17]
## Issue Description
Campo de "adicionar novo" está cortado na página **Usuário**

## Expected behaviour
mostrar placeholder do campo de email

## Reproduction steps
abrir página **Usuários** no IE10

## Extra info
![captura de tela 2016-10-18 as 14 30 44](https://cloud.githubusercontent.com/assets/20709505/19493441/5e948060-9559-11e6-8365-5834228ea4ab.png)

**Comment by phillfer** [comment]
Close #293dd69
