### ISSUE TITLE
Emails cadastrados não retornam nenhum feedback

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-landing#2]
# Descrição
Caso eu tente cadastrar uma nova empresa com um e-mail já cadastrado o loading é iniciado e não retornam nenhum feedback na interface.

# Comportamento esperado
Deixar claro pro usuário que ele não pode cadastrar mais que uma empresa com o mesmo email. 

# Reproduzindo a Issue
tente cadastrar uma nova empresa com um e-mail já cadastrado

**Comment by mathportillo** [comment]
Fixed in 24735dd2b4c1287463e449ef5d95fdae91583fae
