### ISSUE TITLE
Fechar lightbox ao clicar na parte escura, nem sempre funciona

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-landing#20]
## Issue Description
**Tela do Reembolso:** Fechar lightbox ao clicar na parte escura, nem sempre funciona

## Expected behaviour
Fechar lightbox ao clicar fora da área de interesse

## Actual behaviour
De vez enquando o clique fora não desabilita o lightbox

## Reproduction steps
Abrir lightbox clicando no ícone de imagem ou texto na tabela de reembolsos.

**Comment by phillfer** [comment]
#e45118a
